{"name": "En el que valido la app con diferentes contraseñas y passwords -- @1.2 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (/Users/fabiansolano/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.js:75:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Users/fabiansolano/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)\n    at AndroidUiautomator2Driver.findElement (/Users/fabiansolano/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)\n", "trace": "  File \"/Library/Python/3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Library/Python/3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/iniciar_sesion.py\", line 26, in step_impl\n    menu_home_page.verificar_objeto_existe()\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/src/pages/menu_home_page.py\", line 35, in verificar_objeto_existe\n    self.ec_wait(self.CONSULTAR_REGISTRO)\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/src/pages/menu_home_page.py\", line 19, in ec_wait\n    self.wait.until(EC.presence_of_element_located((By.XPATH, locator)))\n  File \"/Library/Python/3.9/site-packages/selenium/webdriver/support/wait.py\", line 87, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Abro la app para poder iniciar sesion", "status": "passed", "start": 1715387422749, "stop": 1715387422749}, {"name": "When Inicio sesion con JOSY43 y Test4321", "status": "passed", "attachments": [{"name": "Evidence", "source": "6cd7b316-c9e1-4531-987f-b5fcb265563c-attachment.png", "type": "image/png"}], "start": 1715387422749, "stop": 1715387427093}, {"name": "Then Valido que se abra el home de la app", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (/Users/fabiansolano/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.js:75:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Users/fabiansolano/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)\n    at AndroidUiautomator2Driver.findElement (/Users/fabiansolano/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)\n", "trace": "  File \"/Library/Python/3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Library/Python/3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/iniciar_sesion.py\", line 26, in step_impl\n    menu_home_page.verificar_objeto_existe()\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/src/pages/menu_home_page.py\", line 35, in verificar_objeto_existe\n    self.ec_wait(self.CONSULTAR_REGISTRO)\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/src/pages/menu_home_page.py\", line 19, in ec_wait\n    self.wait.until(EC.presence_of_element_located((By.XPATH, locator)))\n  File \"/Library/Python/3.9/site-packages/selenium/webdriver/support/wait.py\", line 87, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "attachments": [{"name": "Algo salió mal", "source": "efd465e2-9030-454f-bc6a-b8f520e7b740-attachment.png", "type": "image/png"}], "start": 1715387427093, "stop": 1715387435323}], "parameters": [{"name": "usuario", "value": "JOSY43"}, {"name": "password", "value": "Test4321"}], "start": 1715387419354, "stop": 1715387435325, "uuid": "bde26103-2a6e-4007-9fdb-fc78f53905bd", "historyId": "2c87cd7e3936f1f9d55c428e8f13c70a", "fullName": "Como usuario de la app necesito validar que mis contraseñas son valida para saber cuantos usuarios validos tengo: En el que valido la app con diferentes contraseñas y passwords", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Como usuario de la app necesito validar que mis contraseñas son valida para saber cuantos usuarios validos tengo"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}